CREATE TABLE CONVOCATORIA
( ID_CONVOCATORIA char(8) primary key,
FECHA_INICIAL datetime,
FECHA_FINAL datetime
);

CREATE TABLE ROLES
(ID_ROL char(8) primary key,
NOMBRE_ROL varchar(20)
);

INSERT INTO ROLES (ID_ROL, NOMBRE_ROL)
VALUES ('UPC-00','ADMINISTRADOR');
INSERT INTO ROLES (ID_ROL, NOMBRE_ROL)
VALUES ('UPC-01','DOCENTE');
INSERT INTO ROLES (ID_ROL, NOMBRE_ROL)
VALUES ('UPC-02','EVALUADOR');
INSERT INTO ROLES (ID_ROL, NOMBRE_ROL)
VALUES ('UPC-03','CALIFICADOR');

select * from roles;

CREATE TABLE DOCENTES
( ID_DOCENTE char(12) not null,
PRIMER_APELLIDO varchar(20) not null,
SEGUNDO_APELLIDO varchar(20),
PRIMER_NOMBRE varchar(20) not null,
SEGUNDO_NOMBRE varchar(20),
NOMBRE_ROL varchar(20),
Utilidad float,
CONSTRAINT fk_TIPO_DOCENTE FOREIGN KEY (NOMBRE_ROL) REFERENCES ROLES (NOMBRE_ROL)
);